
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://192.168.51.236:3306/piaoniu?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    enabled: true
    suffix: .html

  redis:
    database: 0
    timeout: 0
    host: 127.0.0.1
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0


mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.piaoniu.demo.dao
